#!/usr/bin/env python3
"""
Build every Cinder brand raster from the one SVG source, and build the
horizontal lockup from an outlined Inter so nothing downstream needs the font.

    python3 scripts/build-brand.py            # dry run, prints what it would write
    python3 scripts/build-brand.py --apply    # write

Source of truth:
    static/brand/cinder-mark.svg   ember on transparent, for dark surfaces

Everything else in static/brand/ and the site's own favicon set are OUTPUTS,
including the light variant: it is the dark mark with the theme's own light
swap applied, so the two can never drift.
Fix the SVG or this script; never hand-edit a PNG.

Why the site icons are regenerated here: the shipped favicon/apple-touch/PWA
icons were screen captures of the AMBIENT Merkaba.svelte mid-rotation, so they
arrived clipped and off-center. They are the mark now.
"""

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRAND = ROOT / "static" / "brand"
STATIC = ROOT / "static"
INTER = Path.home() / "Library" / "Fonts" / "Inter_24pt-SemiBold.ttf"

APPLY = "--apply" in sys.argv

# Stripe's branding settings (docs.stripe.com/get-started/account/branding) take
# JPG or PNG, under 512 KB, at least 128x128. 512 is the largest square the rest
# of this repo already ships, so the icon set tops out there rather than inventing
# a size nothing consumes.
STRIPE_ICONS = [128, 256, 512]

# The site's own set. Sizes come from app.html and manifest.webmanifest — if you
# add one there, add it here, not by hand in a graphics app.
SITE_ICONS = {
    "favicon-32.png": 32,
    "favicon.png": 64,
    "apple-touch-icon.png": 180,
    "icon-192.png": 192,
    "icon-512.png": 512,
}


def write(path: Path, data: bytes | str) -> None:
    if not APPLY:
        print(f"  would write {path.relative_to(ROOT)} ({len(data)} bytes)")
        return
    path.write_bytes(data.encode() if isinstance(data, str) else data)
    print(f"  wrote {path.relative_to(ROOT)} ({len(data)} bytes)")


INK = "#0d0b0a"  # --color-ink, the vault floor


def render(svg: Path, size: int, out: Path, bg: str | None = None, inset: float = 0.0) -> None:
    """rsvg-convert keeps the stroke crisp at small sizes; magick softens it.

    bg fills the canvas instead of leaving it transparent. inset is the fraction
    of the box left empty on every side — a maskable icon gets cropped to a
    circle by the launcher, so its art has to live well inside the square.
    """
    art = round(size * (1 - 2 * inset))
    cmd = ["rsvg-convert", "-w", str(art), "-h", str(art)]
    if bg:
        cmd += ["-b", bg]
    png = subprocess.run(cmd + [str(svg)], check=True, capture_output=True).stdout

    if art != size:
        from io import BytesIO

        from PIL import Image

        canvas = Image.new("RGBA", (size, size), bg or (0, 0, 0, 0))
        art_img = Image.open(BytesIO(png)).convert("RGBA")
        off = (size - art) // 2
        canvas.alpha_composite(art_img, (off, off))
        buf = BytesIO()
        canvas.save(buf, "PNG")
        png = buf.getvalue()

    write(out, png)


def to_light(svg: str) -> str:
    """The theme's own light swap, applied to a mark.

    app.css flips ember #ff6b4a to #e8502a under prefers-color-scheme: light,
    and small ember shapes go to ember-ink #c23d1a because that is the pair that
    clears WCAG AA on warm paper. Same two substitutions, same reason.
    """
    body = svg.replace("#ff6b4a", "#e8502a").replace("#ff8f73", "#c23d1a")
    note = (
        "\n  <!-- GENERATED by scripts/build-brand.py from cinder-mark.svg."
        " Do not hand-edit. -->"
    )
    return body.replace("<title>Cinder</title>", "<title>Cinder</title>" + note, 1)


def wordmark(mark_svg: str) -> str:
    """The 'Cinder' lockup, glyphs converted to paths so the SVG is portable.

    The mark's geometry is LIFTED from cinder-mark.svg rather than repeated here.
    A second copy of those coordinates is a copy that drifts, and the stroke
    weight already had to be changed in two places once.
    """
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.ttLib import TTFont

    font = TTFont(INTER)
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    upm, hmtx = font["head"].unitsPerEm, font["hmtx"]
    cap = font["OS/2"].sCapHeight

    track = -0.005 * upm  # a hair tight, so six letters read as one word
    x, paths = 0.0, []
    for ch in "Cinder":
        name = cmap[ord(ch)]
        pen = SVGPathPen(glyphs)
        glyphs[name].draw(pen)
        if d := pen.getCommands():
            paths.append((x, d))
        x += hmtx[name][0] + track
    advance = x - track  # the trailing letter-space is not part of the word

    # Cap height 26 units against a 64-unit mark: the word sits inside the mark's
    # optical height instead of matching its full extent, which is what stops a
    # wordmark from shouting over the thing it is naming.
    cap_units, gap, baseline = 26.0, 12.0, 45.0
    scale = cap_units / cap
    left = 58.45 + gap  # the mark's right edge, stroke included
    width = round(left + advance * scale + 2)

    # Everything from the first <g> to the closing </svg>: the mark, verbatim.
    art = mark_svg[mark_svg.index("  <g fill=\"none\"") : mark_svg.rindex("</svg>")].rstrip()

    body = "\n      ".join(
        f'<path transform="translate({left + px * scale:.3f} {baseline:.3f}) '
        f'scale({scale:.6f} {-scale:.6f})" d="{d}"/>'
        for px, d in paths
    )
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} 64" width="{width}" height="64" role="img" aria-label="Cinder">
  <title>Cinder</title>
  <!--
    THE HORIZONTAL LOCKUP — the mark plus the word, for Stripe's non-square
    "Logo" slot and anywhere else a wide surface would strand a square icon.

    GENERATED by scripts/build-brand.py. Edit the script, never this file.

    The word is Inter SemiBold converted to outlines, tracked -0.005em, cap
    height 26 against the mark's 64, baseline aligned to the mark's center. No
    font is required to render it.
  -->
{art}
  <g fill="#f1ece4">
      {body}
  </g>
</svg>
"""


def main() -> None:
    if not APPLY:
        print("DRY RUN — pass --apply to write\n")

    dark, light = BRAND / "cinder-mark.svg", BRAND / "cinder-mark-light.svg"
    if not dark.exists():
        sys.exit(f"missing source: {dark}")

    print("light variant:")
    write(light, to_light(dark.read_text()))
    if not APPLY and not light.exists():
        sys.exit("\nlight variant does not exist yet — rerun with --apply")

    print("lockup:")
    lockup = BRAND / "cinder-lockup.svg"
    mark_svg = dark.read_text()
    write(lockup, wordmark(mark_svg))
    # The light lockup is the same swap the two marks make: ember darkens, the
    # center goes to ember-ink, and the word flips from paper-white to near-black.
    write(
        BRAND / "cinder-lockup-light.svg",
        wordmark(mark_svg)
        .replace("#ff6b4a", "#e8502a")
        .replace("#ff8f73", "#c23d1a")
        .replace("#f1ece4", "#241a15"),
    )

    print("stripe icons (>=128px, PNG, <512KB):")
    for size in STRIPE_ICONS:
        render(dark, size, BRAND / f"cinder-icon-{size}.png")
        render(light, size, BRAND / f"cinder-icon-light-{size}.png")

    print("stripe logo (the wide lockup, rasterized at 4x the 64-unit box):")
    if APPLY or lockup.exists():
        png = subprocess.run(
            ["rsvg-convert", "-h", "256", str(lockup)], check=True, capture_output=True
        ).stdout
        write(BRAND / "cinder-logo-256.png", png)

    # Site icons get the vault floor behind them. A transparent favicon inherits
    # whatever the browser or launcher paints, and an ember outline on a white
    # tab strip is the one place this mark disappears.
    print("site icons (regenerated from the mark, on the vault floor):")
    for name, size in SITE_ICONS.items():
        render(dark, size, STATIC / name, bg=INK)

    # Maskable: Android crops to a circle inscribed in the middle 80%, so the
    # art is inset 20% on every side. Without this the mark's six points are
    # sliced off on any launcher that rounds the icon.
    print("maskable icon:")
    render(dark, 512, STATIC / "icon-maskable-512.png", bg=INK, inset=0.20)


if __name__ == "__main__":
    main()
